language: node_js
cache:
- node_modules
node_js:
- stable
after_success: npm run coverage
deploy:
  provider: heroku
  app: darasimi-epicmail
  on: develop
  api_key:
    secure: giPdjUoQ0IARVY7YQ3MgA1VJ+GZm/NDXjOP1fbBAa1J/1h/s3FOx4/BztGQBvjQ9lUrc4TniFdKXcCgGT/cCqXmXDOC7WPwXqkoIld+lr40qLwMlx9Zyddd9NBEEsgekWaEXsZrls8dHE1z586gmHAq4kncsBxMW7UKz5/tZKE6DfYxLmwrT1NQiKfUNisGZSdPjDPm7poNXWnpJzE0/FpD85Ixrhzg/8d4uF+9q6G5pNUpI0jjWwdhQCNurzN3wIR7bY4goAxJBv3YfSnWVSBRqx3eMivCeMe9SnigHt3QhzO07mTiiZevcieYn02A3yqMPq3sWhtmRA0JyL+PFTFsHtmGNZB5aSHaTY67DgFZi1NmpLuKCOoMsCnXOSseWgUVuolBT7qi/Xcu4QUtesI6f67bKkTtCmQREydtjZgdI9DJolTaIBECvdIILOan+4wJZpQgtwrSUPckrxsryTBlsIW27qrFqwTA2RbtKaGaj2P3tojDb2CrdNe0ac+hDUFYFVcA2zKb2GuhwMBOVnEKGXAtITDU9HU2VeFNWpLIU99+QlOT/uAvJ1rZ7sYZ+dstA4HdMzy7YpWKxquKSo/BCCPemXIC6EEELOUPVsAK1Nhck+09s+J5RS4StK6OR0a5DUGRG/vkfvvDmWoCw/u44JBf8obCJ3UFAcIceTSk=
  app: darasimi-epicmail
  on: develop