language: node_js
node_js:
- stable
after_success: npm run coverage
deploy:
  provider: heroku
  app: darasimi-epicmail
  on: develop
  api_key:
    secure: dmUj2n0Zn/zXTo0xSI339+ckOt6GHd+04z2GEDEqor25UjqAzdUFJcmxzR7q53uYPUXe1WpRNFRSFT1nVordIqPyVpvr1GRNRX9+VNtU7/+FkiWJsuhMevBMNGaZQ4SCT/CvxXi6/Ko69tV+MIiLg+uICr5xriiFA43fmkdlsykHPzSdEjHiM8sB7y3he50v/bG+C4GzUKmp2/woQIDs0ctVB6V81cDkYG5TrrqQ6ycjCxvaxpm8pr0CcbZWbl0ZYzq+6RlXf/Fi9s9mz9qJYwvTRolHAicd0c4EHKw9IIE4uJ3reaQ2w7AZJoy17ABDZgTPp16g0D+K+7wOm77MfeXNbMTwiEsjnqLtUgQovCR1D5TOIdCz9XziHz63Vz4uW7mGjyHEpdJLt6zNJmkHSaq47oyDCoAxXPXvwoRrChpfPBGLR51p2jpejT+tF0Awl8QKDMUpXL8oyYzCtyWiE0uyYZhmm/F5gZJGZr5N9GMqnbAJXcZvVvVoOu2ttlVQMFkiSpfOF6HTbtw1LzwQbRPt5uv0+4LWqNatatZZlAOUCxcr/ojqrc720fR107jiJJhGE69iCR19cABDOIYUMmPpMUzCsfcceY13Pq9VCEfII5ibTijJtGM8dAamy8tXFzZS5TlsPdZR6azBvOojIGDjsix2ATTkHagZ66GLPLM=
